#
# Testcase for test/test:RCP_ComputerSystem
#
# Generated by 'genprovider' for use with cmpi-bindings-ruby
require 'rubygems'
require 'sfcc'
require 'test/unit'
require 'provider-testing'

class Test_RCP_BaseProvider < Test::Unit::TestCase
  def setup
    @client, @op = ProviderTesting.setup 'RCP_ComputerSystem', 'test/test'
  end

  def teardown
    ProviderTesting.teardown
  end

  def test_registered
    puts "test_registered #{@op}"
    cimclass = @client.get_class(@op)
    assert cimclass
  end

  def test_instance_names
    puts "test_instance_names #{@op}"
    names = @client.instance_names(@op)
    assert names.size > 0
    names.each do |ref|
      ref.namespace = @op.namespace
      instance = @client.get_instance ref
      assert instance
    
      assert instance.Name
      assert_kind_of String, instance.Name
      assert instance.CreationClassName
      assert_kind_of String, instance.CreationClassName
    end
  end

  def test_exec_query
    query = "select OperationalStatus from #{@op.classname}"
    puts "Query '#{query}'"
    result = @client.query(@op, query, "WQL")
    assert result
    assert_kind_of Sfcc::Cim::Enumeration, result
    result.each do |instance|
      assert instance
      assert_kind_of Sfcc::Cim::Instance, instance
      assert_equal @op.classname, instance.classname
      puts "instance.OperationalStatus #{instance.OperationalStatus.inspect}"
      assert instance.OperationalStatus # this property should be set
      puts "instance.NameFormat #{instance.NameFormat.inspect}"
      assert_nil instance.NameFormat # this property shouldn't be set
    end
  end
end
