#
# Class information for CIM_ManagedSystemElement
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'
require 'mof/CIM_ManagedElement'

module MOF
  class CIM_ManagedSystemElement < CIM_ManagedElement
  end
end
