#
# Class information for CIM_LogicalElement
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'
require 'mof/CIM_ManagedSystemElement'
require 'mof/CIM_ManagedElement'

module MOF
  class CIM_LogicalElement < CIM_ManagedSystemElement
  end
end
