#
# Class information for CIM_EnabledLogicalElement
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'
require 'mof/CIM_LogicalElement'
require 'mof/CIM_ManagedSystemElement'
require 'mof/CIM_ManagedElement'

module MOF
  class CIM_EnabledLogicalElement < CIM_LogicalElement
    METHODS = {
      "RequestStateChange" => { :type => :uint32, :parameters => {:in => ["RequestedState", :uint16, "TimeoutPeriod", :dateTime], :out => ["Job", :class]} }
    }
  end
end
