#
# Class information for CIM_System
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'
require 'mof/CIM_EnabledLogicalElement'
require 'mof/CIM_LogicalElement'
require 'mof/CIM_ManagedSystemElement'
require 'mof/CIM_ManagedElement'

module MOF
  class CIM_System < CIM_EnabledLogicalElement
  end
end
