#
# Class information for CIM_ComputerSystem
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'
require 'mof/CIM_System'
require 'mof/CIM_EnabledLogicalElement'
require 'mof/CIM_LogicalElement'
require 'mof/CIM_ManagedSystemElement'
require 'mof/CIM_ManagedElement'

module MOF
  class CIM_ComputerSystem < CIM_System
    METHODS = {
      "SetPowerState" => { :type => :uint32, :parameters => {:in => ["PowerState", :uint32, "Time", :dateTime]} }
    }
  end
end
