#
# Class information for RCP_ComputerSystem
#
# Generated by 'genprovider' for use with ruby-sfcc

require 'rubygems'
require 'cim'
require 'mof/CIM_ComputerSystem'
require 'mof/CIM_System'
require 'mof/CIM_EnabledLogicalElement'
require 'mof/CIM_LogicalElement'
require 'mof/CIM_ManagedSystemElement'
require 'mof/CIM_ManagedElement'

module MOF
  class RCP_ComputerSystem < CIM_ComputerSystem
  end
end
